set(SRC
    source/main.cpp
    source/presentation/view/window/GUIWindow.cpp
    source/presentation/view/window/GUIWindow.ui
    source/presentation/view/window/GUIWindow.h
    source/presentation/view/menu/FileMenu.cpp
    source/presentation/view/menu/FileMenu.h
    source/presentation/view/gui/GUICenter.cpp
    source/presentation/view/gui/GUICenter.h
    source/domain/model/Image.cpp
    source/domain/model/Series.cpp
    source/domain/model/Study.cpp
    source/domain/model/Patient.cpp
    source/domain/model/Series.h
    source/domain/model/Study.h
    source/domain/model/CoreRepository.h
    source/domain/model/Image.h
    source/domain/model/CoreRepository.cpp
    source/domain/model/Patient.h
)
